### ISSUE TITLE
Are you aware of swagger-tools?

### ISSUE THREAD

**Issue by bebraw** [paulhill/swagger-n#4]
Hi,

Just thought to point out https://github.com/apigee-127/swagger-tools . Maybe check it out, combine efforts or something. :)

**Comment by DinisCruz** [comment]
I also would like to know the differences between **swagger-n** and [swagger-tools](https://github.com/apigee-127/swagger-tools)?

I really like **swagger-n** but before I started using I would like to know the current development state or if is [swagger-tools](https://github.com/apigee-127/swagger-tools)  is more 'production quality'?

**Comment by paulhill** [comment]
swagger-n is about 2 pages of code I whipped up because I needed it. You
can read it all in a few minutes.
It is yours to use as you see fit.

**Comment by DinisCruz** [comment]
And to be honest that is why I really like it and am thinking of using on my project.

The fact that is so simple is really good, and a great re-assurance of Swagger's quality as a spec
