### ISSUE TITLE
Use Coffee-Script for swagger-n.js

### ISSUE THREAD

**Issue by DinisCruz** [paulhill/swagger-n#6]
Looking at https://github.com/paulhill/swagger-n/blob/master/lib/swagger-n.js is really nice and simple

And it would be even better if written in Coffee-Script

That is an accepted idea I'm happy to send a PR with it :)

**Comment by paulhill** [comment]
It was specifically written in JS to be very simple and vanilla. I borrowed
ideas from swagger-jack which is coffee-script.

That said if you want to make a coffee-script version that passes the same
(yet to be written) test suite, that would be cool.
